//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrawlLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrawlLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Entry (Both Lists).
        /// </summary>
        public static string AddEntryBothLists {
            get {
                return ResourceManager.GetString("AddEntryBothLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Child.
        /// </summary>
        public static string AddNewChild {
            get {
                return ResourceManager.GetString("AddNewChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Entry.
        /// </summary>
        public static string AddNewEntry {
            get {
                return ResourceManager.GetString("AddNewEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Next Down.
        /// </summary>
        public static string AddToNextDown {
            get {
                return ResourceManager.GetString("AddToNextDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Next Up.
        /// </summary>
        public static string AddToNextUp {
            get {
                return ResourceManager.GetString("AddToNextUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Parent.
        /// </summary>
        public static string AddToParent {
            get {
                return ResourceManager.GetString("AddToParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to convert the InfFace portraits to the new system as well at this time?.
        /// </summary>
        public static string AlsoConvertInfFacePortraits {
            get {
                return ResourceManager.GetString("AlsoConvertInfFacePortraits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animated GIF.
        /// </summary>
        public static string AnimatedGIF {
            get {
                return ResourceManager.GetString("AnimatedGIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation Data.
        /// </summary>
        public static string AnimationData {
            get {
                return ResourceManager.GetString("AnimationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation Looper.
        /// </summary>
        public static string AnimationLooper {
            get {
                return ResourceManager.GetString("AnimationLooper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append Animation.
        /// </summary>
        public static string AppendAnimation {
            get {
                return ResourceManager.GetString("AppendAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARC Archive.
        /// </summary>
        public static string Archive {
            get {
                return ResourceManager.GetString("Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subspace Resource BLOC.
        /// </summary>
        public static string BLOC {
            get {
                return ResourceManager.GetString("BLOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bone.
        /// </summary>
        public static string Bone {
            get {
                return ResourceManager.GetString("Bone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BRRES Resource Pack.
        /// </summary>
        public static string BRRESourcePack {
            get {
                return ResourceManager.GetString("BRRESourcePack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Sound.
        /// </summary>
        public static string ChangeSound {
            get {
                return ResourceManager.GetString("ChangeSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Spy Textures.
        /// </summary>
        public static string CharacterSpyTextures {
            get {
                return ResourceManager.GetString("CharacterSpyTextures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear List.
        /// </summary>
        public static string ClearList {
            get {
                return ResourceManager.GetString("ClearList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collision.
        /// </summary>
        public static string Collision {
            get {
                return ResourceManager.GetString("Collision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        public static string Collision0x00 {
            get {
                return ResourceManager.GetString("Collision0x00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rock.
        /// </summary>
        public static string Collision0x01 {
            get {
                return ResourceManager.GetString("Collision0x01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grass.
        /// </summary>
        public static string Collision0x02 {
            get {
                return ResourceManager.GetString("Collision0x02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soil.
        /// </summary>
        public static string Collision0x03 {
            get {
                return ResourceManager.GetString("Collision0x03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wood.
        /// </summary>
        public static string Collision0x04 {
            get {
                return ResourceManager.GetString("Collision0x04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Metal.
        /// </summary>
        public static string Collision0x05 {
            get {
                return ResourceManager.GetString("Collision0x05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy Metal.
        /// </summary>
        public static string Collision0x06 {
            get {
                return ResourceManager.GetString("Collision0x06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carpet.
        /// </summary>
        public static string Collision0x07 {
            get {
                return ResourceManager.GetString("Collision0x07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alien.
        /// </summary>
        public static string Collision0x08 {
            get {
                return ResourceManager.GetString("Collision0x08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulborb.
        /// </summary>
        public static string Collision0x09 {
            get {
                return ResourceManager.GetString("Collision0x09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        public static string Collision0x0A {
            get {
                return ResourceManager.GetString("Collision0x0A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rubber.
        /// </summary>
        public static string Collision0x0B {
            get {
                return ResourceManager.GetString("Collision0x0B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slippery.
        /// </summary>
        public static string Collision0x0C {
            get {
                return ResourceManager.GetString("Collision0x0C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow.
        /// </summary>
        public static string Collision0x0D {
            get {
                return ResourceManager.GetString("Collision0x0D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icy Snow.
        /// </summary>
        public static string Collision0x0E {
            get {
                return ResourceManager.GetString("Collision0x0E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game &amp; Watch.
        /// </summary>
        public static string Collision0x0F {
            get {
                return ResourceManager.GetString("Collision0x0F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subspace Ice.
        /// </summary>
        public static string Collision0x10 {
            get {
                return ResourceManager.GetString("Collision0x10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkered.
        /// </summary>
        public static string Collision0x11 {
            get {
                return ResourceManager.GetString("Collision0x11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spikes (Target Test Only).
        /// </summary>
        public static string Collision0x12 {
            get {
                return ResourceManager.GetString("Collision0x12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazard 2 (Subspace Only).
        /// </summary>
        public static string Collision0x13 {
            get {
                return ResourceManager.GetString("Collision0x13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazard 3 (Subspace Only).
        /// </summary>
        public static string Collision0x14 {
            get {
                return ResourceManager.GetString("Collision0x14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electroplankton.
        /// </summary>
        public static string Collision0x15 {
            get {
                return ResourceManager.GetString("Collision0x15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud.
        /// </summary>
        public static string Collision0x16 {
            get {
                return ResourceManager.GetString("Collision0x16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subspace.
        /// </summary>
        public static string Collision0x17 {
            get {
                return ResourceManager.GetString("Collision0x17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stone Bricks.
        /// </summary>
        public static string Collision0x18 {
            get {
                return ResourceManager.GetString("Collision0x18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dustless.
        /// </summary>
        public static string Collision0x19 {
            get {
                return ResourceManager.GetString("Collision0x19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mario Bros..
        /// </summary>
        public static string Collision0x1A {
            get {
                return ResourceManager.GetString("Collision0x1A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grate.
        /// </summary>
        public static string Collision0x1B {
            get {
                return ResourceManager.GetString("Collision0x1B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sand.
        /// </summary>
        public static string Collision0x1C {
            get {
                return ResourceManager.GetString("Collision0x1C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home-Run Contest.
        /// </summary>
        public static string Collision0x1D {
            get {
                return ResourceManager.GetString("Collision0x1D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water (No Splash).
        /// </summary>
        public static string Collision0x1E {
            get {
                return ResourceManager.GetString("Collision0x1E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown 0x1F.
        /// </summary>
        public static string Collision0x1F {
            get {
                return ResourceManager.GetString("Collision0x1F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CollEx.
        /// </summary>
        public static string CollisionExpansion {
            get {
                return ResourceManager.GetString("CollisionExpansion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collision Object.
        /// </summary>
        public static string CollisionObject {
            get {
                return ResourceManager.GetString("CollisionObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceiling.
        /// </summary>
        public static string CollisionTypeCeiling {
            get {
                return ResourceManager.GetString("CollisionTypeCeiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        public static string CollisionTypeFloor {
            get {
                return ResourceManager.GetString("CollisionTypeFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Wall.
        /// </summary>
        public static string CollisionTypeLeftWall {
            get {
                return ResourceManager.GetString("CollisionTypeLeftWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string CollisionTypeNone {
            get {
                return ResourceManager.GetString("CollisionTypeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Wall.
        /// </summary>
        public static string CollisionTypeRightWall {
            get {
                return ResourceManager.GetString("CollisionTypeRightWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Sequence.
        /// </summary>
        public static string ColorSequence {
            get {
                return ResourceManager.GetString("ColorSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Smash.
        /// </summary>
        public static string ColorSmash {
            get {
                return ResourceManager.GetString("ColorSmash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Smashable Textures.
        /// </summary>
        public static string ColorSmashableTextures {
            get {
                return ResourceManager.GetString("ColorSmashableTextures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Smasher.
        /// </summary>
        public static string ColorSmasher {
            get {
                return ResourceManager.GetString("ColorSmasher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more images threw an error when converting. Would you like to try to color smash these regardless? (As opposed to keeping them seperate).
        /// </summary>
        public static string ColorSmashError {
            get {
                return ResourceManager.GetString("ColorSmashError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Files (From Internet).
        /// </summary>
        public static string CommonFilesFromInternet {
            get {
                return ResourceManager.GetString("CommonFilesFromInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you still want to replace this sound?.
        /// </summary>
        public static string ConfirmReplaceSound {
            get {
                return ResourceManager.GetString("ConfirmReplaceSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert InfFace?.
        /// </summary>
        public static string ConvertInfFace {
            get {
                return ResourceManager.GetString("ConvertInfFace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert Stock System.
        /// </summary>
        public static string ConvertStockSystem {
            get {
                return ResourceManager.GetString("ConvertStockSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Node.
        /// </summary>
        public static string CreateNewNode {
            get {
                return ResourceManager.GetString("CreateNewNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSS Slot ID:.
        /// </summary>
        public static string CSSSlotID {
            get {
                return ResourceManager.GetString("CSSSlotID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From CSS List to Random List.
        /// </summary>
        public static string CSSToRandomList {
            get {
                return ResourceManager.GetString("CSSToRandomList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Name.
        /// </summary>
        public static string DefaultName {
            get {
                return ResourceManager.GetString("DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to delete the associated PLT0?.
        /// </summary>
        public static string DeleteAssociatedPLT0 {
            get {
                return ResourceManager.GetString("DeleteAssociatedPLT0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting TEX0.
        /// </summary>
        public static string DeletedTEX0 {
            get {
                return ResourceManager.GetString("DeletedTEX0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echo.
        /// </summary>
        public static string Echo {
            get {
                return ResourceManager.GetString("Echo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit All.
        /// </summary>
        public static string EditAll {
            get {
                return ResourceManager.GetString("EditAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect Data.
        /// </summary>
        public static string EffectData {
            get {
                return ResourceManager.GetString("EffectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following entries also use this sound:.
        /// </summary>
        public static string EntriesUseSound {
            get {
                return ResourceManager.GetString("EntriesUseSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expanded.
        /// </summary>
        public static string Expanded {
            get {
                return ResourceManager.GetString("Expanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export All.
        /// </summary>
        public static string ExportAll {
            get {
                return ResourceManager.GetString("ExportAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Sawnd.
        /// </summary>
        public static string ExportSawnd {
            get {
                return ResourceManager.GetString("ExportSawnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder for InfFace was autodetected to be:.
        /// </summary>
        public static string FolderInfFaceDetected {
            get {
                return ResourceManager.GetString("FolderInfFaceDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Existing.
        /// </summary>
        public static string FromExisting {
            get {
                return ResourceManager.GetString("FromExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From File.
        /// </summary>
        public static string FromFile {
            get {
                return ResourceManager.GetString("FromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        public static string Full {
            get {
                return ResourceManager.GetString("Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Keyframe from Bone Position.
        /// </summary>
        public static string GenerateKeyframe {
            get {
                return ResourceManager.GetString("GenerateKeyframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Keyframes From All Bone Positions.
        /// </summary>
        public static string GenerateKeyframesAll {
            get {
                return ResourceManager.GetString("GenerateKeyframesAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate PAT0.
        /// </summary>
        public static string GeneratePAT0 {
            get {
                return ResourceManager.GetString("GeneratePAT0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        public static string GroupedArchive {
            get {
                return ResourceManager.GetString("GroupedArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Havok Data.
        /// </summary>
        public static string HavokData {
            get {
                return ResourceManager.GetString("HavokData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many textures?.
        /// </summary>
        public static string HowManyTextures {
            get {
                return ResourceManager.GetString("HowManyTextures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID 1.
        /// </summary>
        public static string ID1 {
            get {
                return ResourceManager.GetString("ID1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID 2.
        /// </summary>
        public static string ID2 {
            get {
                return ResourceManager.GetString("ID2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import New Sound.
        /// </summary>
        public static string ImportNewSound {
            get {
                return ResourceManager.GetString("ImportNewSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Sawnd.
        /// </summary>
        public static string ImportSawnd {
            get {
                return ResourceManager.GetString("ImportSawnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Texture.
        /// </summary>
        public static string ImportTexture {
            get {
                return ResourceManager.GetString("ImportTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InfFace conversion successful!.
        /// </summary>
        public static string InfFaceConversionSuccessful {
            get {
                return ResourceManager.GetString("InfFaceConversionSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InfFace Converter.
        /// </summary>
        public static string InfFaceConverter {
            get {
                return ResourceManager.GetString("InfFaceConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input format for textures:.
        /// </summary>
        public static string InputFormatTextures {
            get {
                return ResourceManager.GetString("InputFormatTextures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this correct?.
        /// </summary>
        public static string IsThisCorrect {
            get {
                return ResourceManager.GetString("IsThisCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Generation.
        /// </summary>
        public static string ItemGeneration {
            get {
                return ResourceManager.GetString("ItemGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge Animation.
        /// </summary>
        public static string MergeAnimation {
            get {
                return ResourceManager.GetString("MergeAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc Data.
        /// </summary>
        public static string MiscData {
            get {
                return ResourceManager.GetString("MiscData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Animation.
        /// </summary>
        public static string ModelAnimation {
            get {
                return ResourceManager.GetString("ModelAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Data.
        /// </summary>
        public static string ModelData {
            get {
                return ResourceManager.GetString("ModelData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models.
        /// </summary>
        public static string Models {
            get {
                return ResourceManager.GetString("Models", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        public static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to end of bone array.
        /// </summary>
        public static string MoveEndBoneArray {
            get {
                return ResourceManager.GetString("MoveEndBoneArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        public static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSBin Text File.
        /// </summary>
        public static string MSBin {
            get {
                return ResourceManager.GetString("MSBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Bone Target.
        /// </summary>
        public static string NewBoneTarget {
            get {
                return ResourceManager.GetString("NewBoneTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Color Sequence.
        /// </summary>
        public static string NewColorSequence {
            get {
                return ResourceManager.GetString("NewColorSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Entry.
        /// </summary>
        public static string NewEntry {
            get {
                return ResourceManager.GetString("NewEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Fighter.
        /// </summary>
        public static string NewFighter {
            get {
                return ResourceManager.GetString("NewFighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Group.
        /// </summary>
        public static string NewGroup {
            get {
                return ResourceManager.GetString("NewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Material Entry.
        /// </summary>
        public static string NewMaterialEntry {
            get {
                return ResourceManager.GetString("NewMaterialEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New RE3D Entry.
        /// </summary>
        public static string NewRE3DEntry {
            get {
                return ResourceManager.GetString("NewRE3DEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No convertable InfFace portraits found in.
        /// </summary>
        public static string NoConvertibleInfFacePortrait {
            get {
                return ResourceManager.GetString("NoConvertibleInfFacePortrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;null&gt;.
        /// </summary>
        public static string Null {
            get {
                return ResourceManager.GetString("Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of entries:.
        /// </summary>
        public static string NumberOfEntries {
            get {
                return ResourceManager.GetString("NumberOfEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of runthroughs:.
        /// </summary>
        public static string NumberRunthroughs {
            get {
                return ResourceManager.GetString("NumberRunthroughs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D Models (NW4R).
        /// </summary>
        public static string NW4R3DModels {
            get {
                return ResourceManager.GetString("NW4R3DModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bone Animations (NW4R).
        /// </summary>
        public static string NW4RAnmChr {
            get {
                return ResourceManager.GetString("NW4RAnmChr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Animations (NW4R).
        /// </summary>
        public static string NW4RAnmClr {
            get {
                return ResourceManager.GetString("NW4RAnmClr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture Pattern Animations (NW4R).
        /// </summary>
        public static string NW4RAnmPat {
            get {
                return ResourceManager.GetString("NW4RAnmPat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scene Animations (NW4R).
        /// </summary>
        public static string NW4RAnmScn {
            get {
                return ResourceManager.GetString("NW4RAnmScn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex Animations (NW4R).
        /// </summary>
        public static string NW4RAnmShp {
            get {
                return ResourceManager.GetString("NW4RAnmShp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture Animations (NW4R).
        /// </summary>
        public static string NW4RAnmTexSrt {
            get {
                return ResourceManager.GetString("NW4RAnmTexSrt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility Animations (NW4R).
        /// </summary>
        public static string NW4RAnmVis {
            get {
                return ResourceManager.GetString("NW4RAnmVis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External References.
        /// </summary>
        public static string NW4RExternal {
            get {
                return ResourceManager.GetString("NW4RExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palettes (NW4R).
        /// </summary>
        public static string NW4RPalettes {
            get {
                return ResourceManager.GetString("NW4RPalettes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textures (NW4R).
        /// </summary>
        public static string NW4RTextures {
            get {
                return ResourceManager.GetString("NW4RTextures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset Frame.
        /// </summary>
        public static string OffsetFrame {
            get {
                return ResourceManager.GetString("OffsetFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAT0 Generator.
        /// </summary>
        public static string PAT0Generator {
            get {
                return ResourceManager.GetString("PAT0Generator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Info.
        /// </summary>
        public static string PlayerInfo {
            get {
                return ResourceManager.GetString("PlayerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview All Models.
        /// </summary>
        public static string PreviewAllModels {
            get {
                return ResourceManager.GetString("PreviewAllModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Random List to CSS List.
        /// </summary>
        public static string RandomToCSSList {
            get {
                return ResourceManager.GetString("RandomToCSSList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect.
        /// </summary>
        public static string Redirect {
            get {
                return ResourceManager.GetString("Redirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Encode.
        /// </summary>
        public static string ReEncode {
            get {
                return ResourceManager.GetString("ReEncode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regenerate bone array.
        /// </summary>
        public static string RegenerateBoneArray {
            get {
                return ResourceManager.GetString("RegenerateBoneArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat Animation.
        /// </summary>
        public static string RepeatAnimation {
            get {
                return ResourceManager.GetString("RepeatAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string Replace {
            get {
                return ResourceManager.GetString("Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace All.
        /// </summary>
        public static string ReplaceAll {
            get {
                return ResourceManager.GetString("ReplaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to replace the currently existing.
        /// </summary>
        public static string ReplaceCurrentlyExisting {
            get {
                return ResourceManager.GetString("ReplaceCurrentlyExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize.
        /// </summary>
        public static string Resize {
            get {
                return ResourceManager.GetString("Resize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse Animation.
        /// </summary>
        public static string ReverseAnimation {
            get {
                return ResourceManager.GetString("ReverseAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse to Loop.
        /// </summary>
        public static string ReverseToLoop {
            get {
                return ResourceManager.GetString("ReverseToLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scene Data.
        /// </summary>
        public static string SceneData {
            get {
                return ResourceManager.GetString("SceneData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scene Settings.
        /// </summary>
        public static string SceneSettings {
            get {
                return ResourceManager.GetString("SceneSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Collision Attributes.
        /// </summary>
        public static string SCLA {
            get {
                return ResourceManager.GetString("SCLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to send these through the color smash tool now?.
        /// </summary>
        public static string SendThroughColorSmashTool {
            get {
                return ResourceManager.GetString("SendThroughColorSmashTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Entries.
        /// </summary>
        public static string SortEntries {
            get {
                return ResourceManager.GetString("SortEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Items.
        /// </summary>
        public static string SortItems {
            get {
                return ResourceManager.GetString("SortItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        public static string Sound {
            get {
                return ResourceManager.GetString("Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Bank.
        /// </summary>
        public static string SoundBank {
            get {
                return ResourceManager.GetString("SoundBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spy.
        /// </summary>
        public static string Spy {
            get {
                return ResourceManager.GetString("Spy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Shadow.
        /// </summary>
        public static string StageShadow {
            get {
                return ResourceManager.GetString("StageShadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Shadow Texture.
        /// </summary>
        public static string StageShadowTexture {
            get {
                return ResourceManager.GetString("StageShadowTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Table.
        /// </summary>
        public static string StageTable {
            get {
                return ResourceManager.GetString("StageTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static (Empty) Model.
        /// </summary>
        public static string StaticEmptyModel {
            get {
                return ResourceManager.GetString("StaticEmptyModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Trap Data Table.
        /// </summary>
        public static string STDT {
            get {
                return ResourceManager.GetString("STDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Trap Data Table Generation.
        /// </summary>
        public static string STDTGeneration {
            get {
                return ResourceManager.GetString("STDTGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Parameters.
        /// </summary>
        public static string STPM {
            get {
                return ResourceManager.GetString("STPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STPM Data.
        /// </summary>
        public static string STPMData {
            get {
                return ResourceManager.GetString("STPMData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STPM Entry.
        /// </summary>
        public static string STPMEntry {
            get {
                return ResourceManager.GetString("STPMEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 1.
        /// </summary>
        public static string STPMVal01 {
            get {
                return ResourceManager.GetString("STPMVal01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 2.
        /// </summary>
        public static string STPMVal02 {
            get {
                return ResourceManager.GetString("STPMVal02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 3.
        /// </summary>
        public static string STPMVal03 {
            get {
                return ResourceManager.GetString("STPMVal03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 4.
        /// </summary>
        public static string STPMVal04 {
            get {
                return ResourceManager.GetString("STPMVal04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 5.
        /// </summary>
        public static string STPMVal05 {
            get {
                return ResourceManager.GetString("STPMVal05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadow Vertical Angle.
        /// </summary>
        public static string STPMVal06 {
            get {
                return ResourceManager.GetString("STPMVal06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadow Horizontal Angle.
        /// </summary>
        public static string STPMVal07 {
            get {
                return ResourceManager.GetString("STPMVal07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 8.
        /// </summary>
        public static string STPMVal08 {
            get {
                return ResourceManager.GetString("STPMVal08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 9.
        /// </summary>
        public static string STPMVal09 {
            get {
                return ResourceManager.GetString("STPMVal09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera FOV.
        /// </summary>
        public static string STPMVal10 {
            get {
                return ResourceManager.GetString("STPMVal10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Minimum Z.
        /// </summary>
        public static string STPMVal11 {
            get {
                return ResourceManager.GetString("STPMVal11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Maximum Z.
        /// </summary>
        public static string STPMVal12 {
            get {
                return ResourceManager.GetString("STPMVal12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Minimum Tilt.
        /// </summary>
        public static string STPMVal13 {
            get {
                return ResourceManager.GetString("STPMVal13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Maximum Tilt.
        /// </summary>
        public static string STPMVal14 {
            get {
                return ResourceManager.GetString("STPMVal14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Rotation Factor.
        /// </summary>
        public static string STPMVal15 {
            get {
                return ResourceManager.GetString("STPMVal15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Rotation Factor.
        /// </summary>
        public static string STPMVal16 {
            get {
                return ResourceManager.GetString("STPMVal16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Bubble Buffer Multiplier.
        /// </summary>
        public static string STPMVal17 {
            get {
                return ResourceManager.GetString("STPMVal17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 18.
        /// </summary>
        public static string STPMVal18 {
            get {
                return ResourceManager.GetString("STPMVal18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Speed.
        /// </summary>
        public static string STPMVal19 {
            get {
                return ResourceManager.GetString("STPMVal19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star KO Camera Tilt.
        /// </summary>
        public static string STPMVal20 {
            get {
                return ResourceManager.GetString("STPMVal20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Smash Camera Tilt.
        /// </summary>
        public static string STPMVal21 {
            get {
                return ResourceManager.GetString("STPMVal21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Right Boundary.
        /// </summary>
        public static string STPMVal22 {
            get {
                return ResourceManager.GetString("STPMVal22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Left Boundary.
        /// </summary>
        public static string STPMVal23 {
            get {
                return ResourceManager.GetString("STPMVal23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Camera Default X.
        /// </summary>
        public static string STPMVal24 {
            get {
                return ResourceManager.GetString("STPMVal24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Camera Neutral Position.
        /// </summary>
        public static string STPMVal24_25_26 {
            get {
                return ResourceManager.GetString("STPMVal24-25-26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Camera Default Y.
        /// </summary>
        public static string STPMVal25 {
            get {
                return ResourceManager.GetString("STPMVal25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Camera Default Z.
        /// </summary>
        public static string STPMVal26 {
            get {
                return ResourceManager.GetString("STPMVal26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Camera Default Angle.
        /// </summary>
        public static string STPMVal27 {
            get {
                return ResourceManager.GetString("STPMVal27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Camera Zoom In.
        /// </summary>
        public static string STPMVal28 {
            get {
                return ResourceManager.GetString("STPMVal28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Camera Default Zoom.
        /// </summary>
        public static string STPMVal29 {
            get {
                return ResourceManager.GetString("STPMVal29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Camera Zoom Out.
        /// </summary>
        public static string STPMVal30 {
            get {
                return ResourceManager.GetString("STPMVal30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Camera Y-Rotation Minimum.
        /// </summary>
        public static string STPMVal31 {
            get {
                return ResourceManager.GetString("STPMVal31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Camera Y-Rotation Maximum.
        /// </summary>
        public static string STPMVal32 {
            get {
                return ResourceManager.GetString("STPMVal32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Camera X-Rotation Minimum.
        /// </summary>
        public static string STPMVal33 {
            get {
                return ResourceManager.GetString("STPMVal33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Camera X-Rotation Maximum.
        /// </summary>
        public static string STPMVal34 {
            get {
                return ResourceManager.GetString("STPMVal34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Camera X-Position.
        /// </summary>
        public static string STPMVal35 {
            get {
                return ResourceManager.GetString("STPMVal35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Camera Position.
        /// </summary>
        public static string STPMVal35_36_37 {
            get {
                return ResourceManager.GetString("STPMVal35-36-37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Camera Y-Position.
        /// </summary>
        public static string STPMVal36 {
            get {
                return ResourceManager.GetString("STPMVal36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Camera Z-Position.
        /// </summary>
        public static string STPMVal37 {
            get {
                return ResourceManager.GetString("STPMVal37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Camera Angle.
        /// </summary>
        public static string STPMVal38 {
            get {
                return ResourceManager.GetString("STPMVal38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Camera Horizontal Angle.
        /// </summary>
        public static string STPMVal39 {
            get {
                return ResourceManager.GetString("STPMVal39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Camera Vertical Angle.
        /// </summary>
        public static string STPMVal40 {
            get {
                return ResourceManager.GetString("STPMVal40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 41.
        /// </summary>
        public static string STPMVal41 {
            get {
                return ResourceManager.GetString("STPMVal41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olimar Final Smash Camera Angle.
        /// </summary>
        public static string STPMVal42 {
            get {
                return ResourceManager.GetString("STPMVal42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice Climbers Final Smash X-Position.
        /// </summary>
        public static string STPMVal43 {
            get {
                return ResourceManager.GetString("STPMVal43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice Climbers Final Smash Position.
        /// </summary>
        public static string STPMVal43_44_45 {
            get {
                return ResourceManager.GetString("STPMVal43-44-45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice Climbers Final Smash Y-Position.
        /// </summary>
        public static string STPMVal44 {
            get {
                return ResourceManager.GetString("STPMVal44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice Climbers Final Smash Z-Position.
        /// </summary>
        public static string STPMVal45 {
            get {
                return ResourceManager.GetString("STPMVal45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice Climbers Final Smash X-Scale.
        /// </summary>
        public static string STPMVal46 {
            get {
                return ResourceManager.GetString("STPMVal46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice Climbers Final Smash Scale.
        /// </summary>
        public static string STPMVal46_47 {
            get {
                return ResourceManager.GetString("STPMVal46-47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice Climbers Final Smash Y-Scale.
        /// </summary>
        public static string STPMVal47 {
            get {
                return ResourceManager.GetString("STPMVal47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pit Final Smash Palutena Scale.
        /// </summary>
        public static string STPMVal48 {
            get {
                return ResourceManager.GetString("STPMVal48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 49.
        /// </summary>
        public static string STPMVal49 {
            get {
                return ResourceManager.GetString("STPMVal49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Wind Enabled.
        /// </summary>
        public static string STPMVal50a {
            get {
                return ResourceManager.GetString("STPMVal50a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Wind Enabled.
        /// </summary>
        public static string STPMVal50b {
            get {
                return ResourceManager.GetString("STPMVal50b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 50c.
        /// </summary>
        public static string STPMVal50c {
            get {
                return ResourceManager.GetString("STPMVal50c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 50d.
        /// </summary>
        public static string STPMVal50d {
            get {
                return ResourceManager.GetString("STPMVal50d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind Strength.
        /// </summary>
        public static string STPMVal51 {
            get {
                return ResourceManager.GetString("STPMVal51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Wind Rotation.
        /// </summary>
        public static string STPMVal52 {
            get {
                return ResourceManager.GetString("STPMVal52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Wind Rotation.
        /// </summary>
        public static string STPMVal53 {
            get {
                return ResourceManager.GetString("STPMVal53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 54.
        /// </summary>
        public static string STPMVal54 {
            get {
                return ResourceManager.GetString("STPMVal54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 55.
        /// </summary>
        public static string STPMVal55 {
            get {
                return ResourceManager.GetString("STPMVal55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 56.
        /// </summary>
        public static string STPMVal56 {
            get {
                return ResourceManager.GetString("STPMVal56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 57.
        /// </summary>
        public static string STPMVal57 {
            get {
                return ResourceManager.GetString("STPMVal57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 58.
        /// </summary>
        public static string STPMVal58 {
            get {
                return ResourceManager.GetString("STPMVal58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echo Multiplier.
        /// </summary>
        public static string STPMVal59 {
            get {
                return ResourceManager.GetString("STPMVal59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 60.
        /// </summary>
        public static string STPMVal60 {
            get {
                return ResourceManager.GetString("STPMVal60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 61.
        /// </summary>
        public static string STPMVal61 {
            get {
                return ResourceManager.GetString("STPMVal61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 62.
        /// </summary>
        public static string STPMVal62 {
            get {
                return ResourceManager.GetString("STPMVal62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 63.
        /// </summary>
        public static string STPMVal63 {
            get {
                return ResourceManager.GetString("STPMVal63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 64.
        /// </summary>
        public static string STPMVal64 {
            get {
                return ResourceManager.GetString("STPMVal64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STPM Values.
        /// </summary>
        public static string STPMValues {
            get {
                return ResourceManager.GetString("STPMValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Lists.
        /// </summary>
        public static string SyncLists {
            get {
                return ResourceManager.GetString("SyncLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBCL.
        /// </summary>
        public static string TBCL {
            get {
                return ResourceManager.GetString("TBCL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBCL Generation.
        /// </summary>
        public static string TBCLGeneration {
            get {
                return ResourceManager.GetString("TBCLGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBGC.
        /// </summary>
        public static string TBGC {
            get {
                return ResourceManager.GetString("TBGC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBGC Generation.
        /// </summary>
        public static string TBGCGeneration {
            get {
                return ResourceManager.GetString("TBGCGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBGD.
        /// </summary>
        public static string TBGD {
            get {
                return ResourceManager.GetString("TBGD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBGD Generation.
        /// </summary>
        public static string TBGDGeneration {
            get {
                return ResourceManager.GetString("TBGDGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBGM.
        /// </summary>
        public static string TBGM {
            get {
                return ResourceManager.GetString("TBGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBGM Generation.
        /// </summary>
        public static string TBGMGeneration {
            get {
                return ResourceManager.GetString("TBGMGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBLV.
        /// </summary>
        public static string TBLV {
            get {
                return ResourceManager.GetString("TBLV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBLV Generation.
        /// </summary>
        public static string TBLVGeneration {
            get {
                return ResourceManager.GetString("TBLVGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBRM.
        /// </summary>
        public static string TBRM {
            get {
                return ResourceManager.GetString("TBRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBRM Generation.
        /// </summary>
        public static string TBRMGeneration {
            get {
                return ResourceManager.GetString("TBRMGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBST.
        /// </summary>
        public static string TBST {
            get {
                return ResourceManager.GetString("TBST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBST Generation.
        /// </summary>
        public static string TBSTGeneration {
            get {
                return ResourceManager.GetString("TBSTGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture.
        /// </summary>
        public static string Texture {
            get {
                return ResourceManager.GetString("Texture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture Animation.
        /// </summary>
        public static string TextureAnimation {
            get {
                return ResourceManager.GetString("TextureAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture Data.
        /// </summary>
        public static string TextureData {
            get {
                return ResourceManager.GetString("TextureData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture Pattern.
        /// </summary>
        public static string TexturePattern {
            get {
                return ResourceManager.GetString("TexturePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textures.
        /// </summary>
        public static string Textures {
            get {
                return ResourceManager.GetString("Textures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type 6.
        /// </summary>
        public static string Type6 {
            get {
                return ResourceManager.GetString("Type6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Data.
        /// </summary>
        public static string UnknownData {
            get {
                return ResourceManager.GetString("UnknownData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertex Morph.
        /// </summary>
        public static string VertexMorph {
            get {
                return ResourceManager.GetString("VertexMorph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View File.
        /// </summary>
        public static string ViewFile {
            get {
                return ResourceManager.GetString("ViewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Interpolation.
        /// </summary>
        public static string ViewInterpolation {
            get {
                return ResourceManager.GetString("ViewInterpolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility Sequence.
        /// </summary>
        public static string VisibilitySequence {
            get {
                return ResourceManager.GetString("VisibilitySequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to BrawlCrate v0.24!
        ///
        ///A full English-language changelog can be found here:.
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
