//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrawlLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrawlLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        public static string Collision0x00 {
            get {
                return ResourceManager.GetString("Collision0x00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rock.
        /// </summary>
        public static string Collision0x01 {
            get {
                return ResourceManager.GetString("Collision0x01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grass.
        /// </summary>
        public static string Collision0x02 {
            get {
                return ResourceManager.GetString("Collision0x02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soil.
        /// </summary>
        public static string Collision0x03 {
            get {
                return ResourceManager.GetString("Collision0x03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wood.
        /// </summary>
        public static string Collision0x04 {
            get {
                return ResourceManager.GetString("Collision0x04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Metal.
        /// </summary>
        public static string Collision0x05 {
            get {
                return ResourceManager.GetString("Collision0x05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy Metal.
        /// </summary>
        public static string Collision0x06 {
            get {
                return ResourceManager.GetString("Collision0x06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carpet.
        /// </summary>
        public static string Collision0x07 {
            get {
                return ResourceManager.GetString("Collision0x07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alien.
        /// </summary>
        public static string Collision0x08 {
            get {
                return ResourceManager.GetString("Collision0x08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulborb.
        /// </summary>
        public static string Collision0x09 {
            get {
                return ResourceManager.GetString("Collision0x09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        public static string Collision0x0A {
            get {
                return ResourceManager.GetString("Collision0x0A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rubber.
        /// </summary>
        public static string Collision0x0B {
            get {
                return ResourceManager.GetString("Collision0x0B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slippery.
        /// </summary>
        public static string Collision0x0C {
            get {
                return ResourceManager.GetString("Collision0x0C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow.
        /// </summary>
        public static string Collision0x0D {
            get {
                return ResourceManager.GetString("Collision0x0D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icy Snow.
        /// </summary>
        public static string Collision0x0E {
            get {
                return ResourceManager.GetString("Collision0x0E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game &amp; Watch.
        /// </summary>
        public static string Collision0x0F {
            get {
                return ResourceManager.GetString("Collision0x0F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subspace Ice.
        /// </summary>
        public static string Collision0x10 {
            get {
                return ResourceManager.GetString("Collision0x10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkered.
        /// </summary>
        public static string Collision0x11 {
            get {
                return ResourceManager.GetString("Collision0x11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spikes (Target Test Only).
        /// </summary>
        public static string Collision0x12 {
            get {
                return ResourceManager.GetString("Collision0x12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazard 2 (Subspace Only).
        /// </summary>
        public static string Collision0x13 {
            get {
                return ResourceManager.GetString("Collision0x13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazard 3 (Subspace Only).
        /// </summary>
        public static string Collision0x14 {
            get {
                return ResourceManager.GetString("Collision0x14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electroplankton.
        /// </summary>
        public static string Collision0x15 {
            get {
                return ResourceManager.GetString("Collision0x15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud.
        /// </summary>
        public static string Collision0x16 {
            get {
                return ResourceManager.GetString("Collision0x16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subspace.
        /// </summary>
        public static string Collision0x17 {
            get {
                return ResourceManager.GetString("Collision0x17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stone Bricks.
        /// </summary>
        public static string Collision0x18 {
            get {
                return ResourceManager.GetString("Collision0x18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dustless.
        /// </summary>
        public static string Collision0x19 {
            get {
                return ResourceManager.GetString("Collision0x19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mario Bros..
        /// </summary>
        public static string Collision0x1A {
            get {
                return ResourceManager.GetString("Collision0x1A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grate.
        /// </summary>
        public static string Collision0x1B {
            get {
                return ResourceManager.GetString("Collision0x1B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sand.
        /// </summary>
        public static string Collision0x1C {
            get {
                return ResourceManager.GetString("Collision0x1C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home-Run Contest.
        /// </summary>
        public static string Collision0x1D {
            get {
                return ResourceManager.GetString("Collision0x1D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water (No Splash).
        /// </summary>
        public static string Collision0x1E {
            get {
                return ResourceManager.GetString("Collision0x1E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown 0x1F.
        /// </summary>
        public static string Collision0x1F {
            get {
                return ResourceManager.GetString("Collision0x1F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CollEx.
        /// </summary>
        public static string CollisionExpansion {
            get {
                return ResourceManager.GetString("CollisionExpansion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceiling.
        /// </summary>
        public static string CollisionTypeCeiling {
            get {
                return ResourceManager.GetString("CollisionTypeCeiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        public static string CollisionTypeFloor {
            get {
                return ResourceManager.GetString("CollisionTypeFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Wall.
        /// </summary>
        public static string CollisionTypeLeftWall {
            get {
                return ResourceManager.GetString("CollisionTypeLeftWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string CollisionTypeNone {
            get {
                return ResourceManager.GetString("CollisionTypeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Wall.
        /// </summary>
        public static string CollisionTypeRightWall {
            get {
                return ResourceManager.GetString("CollisionTypeRightWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echo.
        /// </summary>
        public static string Echo {
            get {
                return ResourceManager.GetString("Echo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID 1.
        /// </summary>
        public static string ID1 {
            get {
                return ResourceManager.GetString("ID1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID 2.
        /// </summary>
        public static string ID2 {
            get {
                return ResourceManager.GetString("ID2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STPM Data.
        /// </summary>
        public static string STPMData {
            get {
                return ResourceManager.GetString("STPMData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STPM Entry.
        /// </summary>
        public static string STPMEntry {
            get {
                return ResourceManager.GetString("STPMEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 1.
        /// </summary>
        public static string STPMVal01 {
            get {
                return ResourceManager.GetString("STPMVal01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 2.
        /// </summary>
        public static string STPMVal02 {
            get {
                return ResourceManager.GetString("STPMVal02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 3.
        /// </summary>
        public static string STPMVal03 {
            get {
                return ResourceManager.GetString("STPMVal03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 4.
        /// </summary>
        public static string STPMVal04 {
            get {
                return ResourceManager.GetString("STPMVal04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 5.
        /// </summary>
        public static string STPMVal05 {
            get {
                return ResourceManager.GetString("STPMVal05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadow Vertical Angle.
        /// </summary>
        public static string STPMVal06 {
            get {
                return ResourceManager.GetString("STPMVal06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadow Horizontal Angle.
        /// </summary>
        public static string STPMVal07 {
            get {
                return ResourceManager.GetString("STPMVal07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 8.
        /// </summary>
        public static string STPMVal08 {
            get {
                return ResourceManager.GetString("STPMVal08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 9.
        /// </summary>
        public static string STPMVal09 {
            get {
                return ResourceManager.GetString("STPMVal09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera FOV.
        /// </summary>
        public static string STPMVal10 {
            get {
                return ResourceManager.GetString("STPMVal10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Minimum Z.
        /// </summary>
        public static string STPMVal11 {
            get {
                return ResourceManager.GetString("STPMVal11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Maximum Z.
        /// </summary>
        public static string STPMVal12 {
            get {
                return ResourceManager.GetString("STPMVal12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Minimum Tilt.
        /// </summary>
        public static string STPMVal13 {
            get {
                return ResourceManager.GetString("STPMVal13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Maximum Tilt.
        /// </summary>
        public static string STPMVal14 {
            get {
                return ResourceManager.GetString("STPMVal14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Rotation Factor.
        /// </summary>
        public static string STPMVal15 {
            get {
                return ResourceManager.GetString("STPMVal15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Rotation Factor.
        /// </summary>
        public static string STPMVal16 {
            get {
                return ResourceManager.GetString("STPMVal16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Bubble Buffer Multiplier.
        /// </summary>
        public static string STPMVal17 {
            get {
                return ResourceManager.GetString("STPMVal17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 18.
        /// </summary>
        public static string STPMVal18 {
            get {
                return ResourceManager.GetString("STPMVal18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Speed.
        /// </summary>
        public static string STPMVal19 {
            get {
                return ResourceManager.GetString("STPMVal19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star KO Camera Tilt.
        /// </summary>
        public static string STPMVal20 {
            get {
                return ResourceManager.GetString("STPMVal20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Smash Camera Tilt.
        /// </summary>
        public static string STPMVal21 {
            get {
                return ResourceManager.GetString("STPMVal21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Right Boundary.
        /// </summary>
        public static string STPMVal22 {
            get {
                return ResourceManager.GetString("STPMVal22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Left Boundary.
        /// </summary>
        public static string STPMVal23 {
            get {
                return ResourceManager.GetString("STPMVal23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Camera Default X.
        /// </summary>
        public static string STPMVal24 {
            get {
                return ResourceManager.GetString("STPMVal24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Camera Neutral Position.
        /// </summary>
        public static string STPMVal24_25_26 {
            get {
                return ResourceManager.GetString("STPMVal24-25-26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Camera Default Y.
        /// </summary>
        public static string STPMVal25 {
            get {
                return ResourceManager.GetString("STPMVal25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Camera Default Z.
        /// </summary>
        public static string STPMVal26 {
            get {
                return ResourceManager.GetString("STPMVal26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Camera Default Angle.
        /// </summary>
        public static string STPMVal27 {
            get {
                return ResourceManager.GetString("STPMVal27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Camera Zoom In.
        /// </summary>
        public static string STPMVal28 {
            get {
                return ResourceManager.GetString("STPMVal28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Camera Default Zoom.
        /// </summary>
        public static string STPMVal29 {
            get {
                return ResourceManager.GetString("STPMVal29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Camera Zoom Out.
        /// </summary>
        public static string STPMVal30 {
            get {
                return ResourceManager.GetString("STPMVal30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Camera Y-Rotation Minimum.
        /// </summary>
        public static string STPMVal31 {
            get {
                return ResourceManager.GetString("STPMVal31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Camera Y-Rotation Maximum.
        /// </summary>
        public static string STPMVal32 {
            get {
                return ResourceManager.GetString("STPMVal32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Camera X-Rotation Minimum.
        /// </summary>
        public static string STPMVal33 {
            get {
                return ResourceManager.GetString("STPMVal33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Camera X-Rotation Maximum.
        /// </summary>
        public static string STPMVal34 {
            get {
                return ResourceManager.GetString("STPMVal34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Camera X-Position.
        /// </summary>
        public static string STPMVal35 {
            get {
                return ResourceManager.GetString("STPMVal35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Camera Position.
        /// </summary>
        public static string STPMVal35_36_37 {
            get {
                return ResourceManager.GetString("STPMVal35-36-37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Camera Y-Position.
        /// </summary>
        public static string STPMVal36 {
            get {
                return ResourceManager.GetString("STPMVal36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Camera Z-Position.
        /// </summary>
        public static string STPMVal37 {
            get {
                return ResourceManager.GetString("STPMVal37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Camera Angle.
        /// </summary>
        public static string STPMVal38 {
            get {
                return ResourceManager.GetString("STPMVal38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Camera Horizontal Angle.
        /// </summary>
        public static string STPMVal39 {
            get {
                return ResourceManager.GetString("STPMVal39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Camera Vertical Angle.
        /// </summary>
        public static string STPMVal40 {
            get {
                return ResourceManager.GetString("STPMVal40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 41.
        /// </summary>
        public static string STPMVal41 {
            get {
                return ResourceManager.GetString("STPMVal41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olimar Final Smash Camera Angle.
        /// </summary>
        public static string STPMVal42 {
            get {
                return ResourceManager.GetString("STPMVal42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice Climbers Final Smash X-Position.
        /// </summary>
        public static string STPMVal43 {
            get {
                return ResourceManager.GetString("STPMVal43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice Climbers Final Smash Position.
        /// </summary>
        public static string STPMVal43_44_45 {
            get {
                return ResourceManager.GetString("STPMVal43-44-45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice Climbers Final Smash Y-Position.
        /// </summary>
        public static string STPMVal44 {
            get {
                return ResourceManager.GetString("STPMVal44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice Climbers Final Smash Z-Position.
        /// </summary>
        public static string STPMVal45 {
            get {
                return ResourceManager.GetString("STPMVal45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice Climbers Final Smash X-Scale.
        /// </summary>
        public static string STPMVal46 {
            get {
                return ResourceManager.GetString("STPMVal46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice Climbers Final Smash Scale.
        /// </summary>
        public static string STPMVal46_47 {
            get {
                return ResourceManager.GetString("STPMVal46-47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ice Climbers Final Smash Y-Scale.
        /// </summary>
        public static string STPMVal47 {
            get {
                return ResourceManager.GetString("STPMVal47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pit Final Smash Palutena Scale.
        /// </summary>
        public static string STPMVal48 {
            get {
                return ResourceManager.GetString("STPMVal48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 49.
        /// </summary>
        public static string STPMVal49 {
            get {
                return ResourceManager.GetString("STPMVal49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Wind Enabled.
        /// </summary>
        public static string STPMVal50a {
            get {
                return ResourceManager.GetString("STPMVal50a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Wind Enabled.
        /// </summary>
        public static string STPMVal50b {
            get {
                return ResourceManager.GetString("STPMVal50b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 50c.
        /// </summary>
        public static string STPMVal50c {
            get {
                return ResourceManager.GetString("STPMVal50c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 50d.
        /// </summary>
        public static string STPMVal50d {
            get {
                return ResourceManager.GetString("STPMVal50d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind Strength.
        /// </summary>
        public static string STPMVal51 {
            get {
                return ResourceManager.GetString("STPMVal51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Wind Rotation.
        /// </summary>
        public static string STPMVal52 {
            get {
                return ResourceManager.GetString("STPMVal52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Wind Rotation.
        /// </summary>
        public static string STPMVal53 {
            get {
                return ResourceManager.GetString("STPMVal53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 54.
        /// </summary>
        public static string STPMVal54 {
            get {
                return ResourceManager.GetString("STPMVal54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 55.
        /// </summary>
        public static string STPMVal55 {
            get {
                return ResourceManager.GetString("STPMVal55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 56.
        /// </summary>
        public static string STPMVal56 {
            get {
                return ResourceManager.GetString("STPMVal56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 57.
        /// </summary>
        public static string STPMVal57 {
            get {
                return ResourceManager.GetString("STPMVal57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 58.
        /// </summary>
        public static string STPMVal58 {
            get {
                return ResourceManager.GetString("STPMVal58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echo Multiplier.
        /// </summary>
        public static string STPMVal59 {
            get {
                return ResourceManager.GetString("STPMVal59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 60.
        /// </summary>
        public static string STPMVal60 {
            get {
                return ResourceManager.GetString("STPMVal60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 61.
        /// </summary>
        public static string STPMVal61 {
            get {
                return ResourceManager.GetString("STPMVal61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 62.
        /// </summary>
        public static string STPMVal62 {
            get {
                return ResourceManager.GetString("STPMVal62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 63.
        /// </summary>
        public static string STPMVal63 {
            get {
                return ResourceManager.GetString("STPMVal63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 64.
        /// </summary>
        public static string STPMVal64 {
            get {
                return ResourceManager.GetString("STPMVal64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STPM Values.
        /// </summary>
        public static string STPMValues {
            get {
                return ResourceManager.GetString("STPMValues", resourceCulture);
            }
        }
    }
}
